"""American to British spelling, for dictating in English.

The speech model knows languages, not countries: there is one English
and it was trained mostly on American text, so it spells the American
way whatever your accent. This is the list that puts it right, applied
to the transcript after the fact.

Every entry has to be safe in every sentence, which rules out a whole
class of words a spelling list would normally carry. "Check" is a
cheque only sometimes; "practice" is the noun in both countries;
"program" stays a program on a computer; "tire", "curb", "draft",
"story" and "disk" all mean something of their own. Those are left
alone rather than corrected wrongly, and so are the pairs where both
spellings are good British English - burned and burnt, yogurt, enquiry,
medieval, fetus.

Most of the list is built rather than typed, from a stem and the
endings that stem really takes. Building can invent a word nobody says
- "colourful" is wanted, "colourable" is not - and that costs nothing,
because a key never typed is a key never matched. What it must never do
is give a real word the wrong British form, which is why endings that
drop the extra letter (honorary, humorous, laborious, vaporise) are
generated by no group here.
"""

# SPDX-License-Identifier: GPL-3.0-or-later


def _grow(stems, endings, old, new):
    """stem + ending, with `old` swapped for `new` on the British side."""
    out = {}
    for stem in stems:
        for end in endings:
            out[stem + end] = stem.replace(old, new) + end
    return out


def _grow_end(stems, endings, old, new):
    """As above, but the swap is in the ending rather than the stem."""
    out = {}
    for stem in stems:
        for end in endings:
            out[stem + end] = stem + end.replace(old, new)
    return out


# -or -> -our. Endings that keep the u only; -ous, -ary and -ific drop
# it in British English too, so they are deliberately absent.
_OUR_STEMS = (
    "color", "honor", "favor", "flavor", "savor", "labor", "neighbor",
    "harbor", "humor", "rumor", "vapor", "odor", "armor", "candor",
    "clamor", "splendor", "valor", "vigor", "parlor", "tumor", "endeavor",
    "behavior", "arbor", "ardor", "demeanor", "fervor", "rigor", "succor",
)
_OUR_ENDS = ("", "s", "ed", "ing", "er", "ers", "ful", "fully", "less",
             "lessly", "able", "ably", "ite", "ites", "hood", "hoods",
             "al", "ally", "y", "ies")

# -ize -> -ise, and the nouns built on it. The stems are listed one by
# one because rules cannot tell organize from capsize.
_ISE_STEMS = (
    "apolog", "author", "capital", "categor", "central", "colon", "critic",
    "custom", "digit", "emphas", "fertil", "harmon", "hospital",
    "hypothes", "idol", "immun", "individual", "industrial", "initial",
    "internal", "item", "jeopard", "legal", "liberal", "local", "magnet",
    "marginal", "material", "maxim", "mechan", "memor", "mesmer",
    "metabol", "militar", "minim", "mobil", "modern", "monopol", "moral",
    "national", "natural", "neutral", "normal", "notar", "optim", "organ",
    "ostrac", "oxid", "pasteur", "patron", "penal", "personal", "plagiar",
    "polar", "popular", "pressur", "priorit", "private", "public",
    "pulver", "quant", "radical", "random", "rational", "real", "recogn",
    "reorgan", "revital", "revolution", "ritual", "romantic", "satir",
    "scandal", "scrutin", "secular", "sensational", "social", "special",
    "stabil", "standard", "steril", "subsid", "summar", "sympath",
    "symbol", "synchron", "synthes", "systemat", "tantal", "terror",
    "theor", "trivial", "urban", "util", "vandal", "vapor", "verbal",
    "victim", "visual", "vital", "vocal", "vulcan", "western",
)
_ISE_ENDS = ("ize", "izes", "ized", "izing", "ization", "izations",
             "izer", "izers", "izable")

# -yze -> -yse.
_YSE_STEMS = ("anal", "paral", "catal", "breathal")
_YSE_ENDS = ("yze", "yzes", "yzed", "yzing", "yzer", "yzers")

# -re words, one by one: center takes centred, not centreed, and
# diameter is diameter in both countries.
_RE = {
    "center": "centre", "centers": "centres", "centered": "centred",
    "centering": "centring", "centerpiece": "centrepiece",
    "epicenter": "epicentre", "theater": "theatre", "theaters": "theatres",
    "liter": "litre", "liters": "litres",
    "milliliter": "millilitre", "milliliters": "millilitres",
    "kilometer": "kilometre", "kilometers": "kilometres",
    "centimeter": "centimetre", "centimeters": "centimetres",
    "millimeter": "millimetre", "millimeters": "millimetres",
    "nanometer": "nanometre", "nanometers": "nanometres",
    "fiber": "fibre", "fibers": "fibres", "fiberglass": "fibreglass",
    "caliber": "calibre", "calibers": "calibres",
    "somber": "sombre", "somberly": "sombrely",
    "specter": "spectre", "specters": "spectres",
    "luster": "lustre", "lackluster": "lacklustre",
    "saber": "sabre", "sabers": "sabres",
    "scepter": "sceptre", "ocher": "ochre",
    "maneuver": "manoeuvre", "maneuvers": "manoeuvres",
    "maneuvered": "manoeuvred", "maneuvering": "manoeuvring",
    "maneuverable": "manoeuvrable",
}

# One l in America, two here.
_LL = {
    "traveled": "travelled", "traveling": "travelling",
    "traveler": "traveller", "travelers": "travellers",
    "canceled": "cancelled", "canceling": "cancelling",
    "modeled": "modelled", "modeling": "modelling",
    "modeler": "modeller", "labeled": "labelled", "labeling": "labelling",
    "marveled": "marvelled", "marveling": "marvelling",
    "marvelous": "marvellous", "marvelously": "marvellously",
    "counseled": "counselled", "counseling": "counselling",
    "counselor": "counsellor", "counselors": "counsellors",
    "jeweler": "jeweller", "jewelers": "jewellers",
    "jewelry": "jewellery",
    "signaled": "signalled", "signaling": "signalling",
    "totaled": "totalled", "totaling": "totalling",
    "fueled": "fuelled", "fueling": "fuelling",
    "refueled": "refuelled", "refueling": "refuelling",
    "dialed": "dialled", "dialing": "dialling",
    "equaled": "equalled", "equaling": "equalling",
    "quarreled": "quarrelled", "quarreling": "quarrelling",
    "rivaled": "rivalled", "rivaling": "rivalling",
    "tunneled": "tunnelled", "tunneling": "tunnelling",
    "unraveled": "unravelled", "unraveling": "unravelling",
    "initialed": "initialled",
    "funneled": "funnelled", "funneling": "funnelling",
    "paneled": "panelled", "paneling": "panelling",
    "leveled": "levelled", "leveling": "levelling",
    "shoveled": "shovelled", "shoveling": "shovelling",
    "spiraled": "spiralled", "spiraling": "spiralling",
    "groveled": "grovelled", "snorkeled": "snorkelled",
    "worshiped": "worshipped", "worshiping": "worshipping",
    "worshiper": "worshipper",
    "woolen": "woollen", "woolens": "woollens", "wooly": "woolly",
    "tranquility": "tranquillity",
    # ...and two in America, one here.
    "willful": "wilful", "willfully": "wilfully",
    "skillful": "skilful", "skillfully": "skilfully",
    "fulfill": "fulfil", "fulfills": "fulfils",
    "fulfillment": "fulfilment",
    "enroll": "enrol", "enrolls": "enrols", "enrollment": "enrolment",
    "installment": "instalment", "installments": "instalments",
    "distill": "distil", "distills": "distils",
    "instill": "instil", "instills": "instils",
    "appall": "appal", "appalls": "appals",
    "enthrall": "enthral", "enthralls": "enthrals",
}

# -ense -> -ence. Only the nouns: defensive and offensive are the same
# either side, and licence-the-noun cannot be told from license-the-verb.
_ENCE = {
    "defense": "defence", "defenses": "defences",
    "defenseless": "defenceless",
    "offense": "offence", "offenses": "offences",
    "pretense": "pretence", "pretenses": "pretences",
}

# -og -> -ogue.
_OGUE = {
    "catalog": "catalogue", "catalogs": "catalogues",
    "cataloged": "catalogued", "cataloging": "cataloguing",
    "dialog": "dialogue", "dialogs": "dialogues",
    "monolog": "monologue", "monologs": "monologues",
    "analog": "analogue", "analogs": "analogues",
    "epilog": "epilogue", "epilogs": "epilogues",
}

# The ae and oe words, mostly medical, where American English closed up
# the vowel pair.
_AE = {
    "anesthesia": "anaesthesia", "anesthetic": "anaesthetic",
    "anesthetics": "anaesthetics", "anesthetist": "anaesthetist",
    "archeology": "archaeology", "archeological": "archaeological",
    "archeologist": "archaeologist", "archeologists": "archaeologists",
    "paleontology": "palaeontology",
    "esthetic": "aesthetic", "esthetics": "aesthetics",
    "esthetically": "aesthetically",
    "anemia": "anaemia", "anemic": "anaemic",
    "diarrhea": "diarrhoea", "edema": "oedema", "celiac": "coeliac",
    "esophagus": "oesophagus", "estrogen": "oestrogen",
    "gynecology": "gynaecology", "gynecologist": "gynaecologist",
    "gynecological": "gynaecological",
    "hemoglobin": "haemoglobin", "hemorrhage": "haemorrhage",
    "hemorrhaging": "haemorrhaging", "hemorrhoids": "haemorrhoids",
    "leukemia": "leukaemia",
    "orthopedic": "orthopaedic", "orthopedics": "orthopaedics",
    "pediatric": "paediatric", "pediatrics": "paediatrics",
    "pediatrician": "paediatrician",
}

# Everything else that is simply spelt differently.
_ODD = {
    "airplane": "aeroplane", "airplanes": "aeroplanes",
    "aluminum": "aluminium", "ax": "axe",
    "gray": "grey", "grayer": "greyer", "grayish": "greyish",
    "grayscale": "greyscale",
    "mold": "mould", "molds": "moulds", "molded": "moulded",
    "molding": "moulding", "moldy": "mouldy",
    "molt": "moult", "molting": "moulting",
    "smolder": "smoulder", "smoldering": "smouldering",
    "mustache": "moustache", "mustaches": "moustaches",
    "pajamas": "pyjamas", "plow": "plough", "plows": "ploughs",
    "plowed": "ploughed", "plowing": "ploughing",
    "skeptic": "sceptic", "skeptics": "sceptics",
    "skeptical": "sceptical", "skeptically": "sceptically",
    "skepticism": "scepticism",
    "sulfur": "sulphur", "sulfuric": "sulphuric", "sulfide": "sulphide",
    "cozy": "cosy", "cozier": "cosier", "coziness": "cosiness",
    "donut": "doughnut", "donuts": "doughnuts",
    "tidbit": "titbit", "math": "maths",
    "aging": "ageing", "judgment": "judgement", "judgments": "judgements",
    "specialty": "speciality", "specialties": "specialities",
    "likable": "likeable", "sizable": "sizeable", "salable": "saleable",
    "unshakable": "unshakeable",
    "artifact": "artefact", "artifacts": "artefacts",
    "omelet": "omelette", "omelets": "omelettes",
    "chili": "chilli", "chilies": "chillies",
}


def _build():
    words = {}
    words.update(_grow(_OUR_STEMS, _OUR_ENDS, "or", "our"))
    words.update(_grow_end(_ISE_STEMS, _ISE_ENDS, "iz", "is"))
    words.update(_grow_end(_YSE_STEMS, _YSE_ENDS, "yz", "ys"))
    for group in (_RE, _LL, _ENCE, _OGUE, _AE, _ODD):
        words.update(group)
    # A word that is already British must never be a key, or the two
    # entries fight and the text changes on every pass.
    british = set(words.values())
    return {k: v for k, v in words.items() if k not in british}


BRITISH = _build()
